### ISSUE TITLE
Erro na title NITFBasicTile ao atualizar da versão 1.0.4 para versão 1.0.5

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#123]
@Dadlo 
@hvelarde 
@macagua

O release 1.0.5 do brasil.gov.portal atualizou o brasil.gov.tiles da versão 1.0.4 para a versão 1.0.5:

https://github.com/plonegovbr/portalpadrao.release/commit/248ff2a253871674b1912c405d2902d30154d6fe#diff-31e777f7c24a7b1db14ecf916a23748bR462

No entanto, se um portal estava com a versão 1.0.4 do brasil.gov.tiles e possui uma tile NITFBasicTile com o campo 'variacao_titulo' preenchido com 'Grande' ou 'Gigante', e depois atualizarmos o brasil.gov.tiles para versão 1.0.5, ocorre o erro:

    2014-12-12 12:05:00 ERROR plone.subrequest Error handling subrequest to http://localhost:8080/site/home/@@nitf/acf7fd26b8064bfd92d4da77e65c0046
    Traceback (most recent call last):
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/plone.subrequest-1.6.8-py2.7.egg/plone/subrequest/__init__.py", line 124, in subrequest
        bind=1)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/mapply.py", line 78, in mapply
        else: return object(*args)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/plone.tiles-1.2-py2.7.egg/plone/tiles/esi.py", line 56, in __call__
        return self.index(*args, **kwargs)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/viewpagetemplatefile.py", line 83, in __call__
        return self.im_func(im_self, *args, **kw)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/viewpagetemplatefile.py", line 51, in __call__
        sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
        strictinsert=0, sourceAnnotations=sourceAnnotations
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/five.pt-2.2.2-py2.7.egg/five/pt/engine.py", line 93, in __call__
        return self.template.render(**kwargs)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
        return base_renderer(**context)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/Chameleon-2.16-py2.7.egg/chameleon/zpt/template.py", line 258, in render
        return super(PageTemplate, self).render(**vars)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/Chameleon-2.16-py2.7.egg/chameleon/template.py", line 188, in render
        raise_with_traceback(exc, tb)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/Chameleon-2.16-py2.7.egg/chameleon/template.py", line 170, in render
        self._render(stream, econtext, rcontext)
      File "85ff51296b9e31180df64c2e6b517d11.py", line 352, in render
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/five.pt-2.2.2-py2.7.egg/five/pt/expressions.py", line 161, in __call__
        return base()
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/brasil.gov.tiles-1.0.5-py2.7.egg/brasil/gov/tiles/tiles/nitf.py", line 72, in variacao_titulo
        return tamanhos[self.data['variacao_titulo']]
    KeyError: u'Gigante'
    
     - Expression: "view/variacao_titulo"
     - Filename:   ... 1.0.5-py2.7.egg/brasil/gov/tiles/tiles/templates/nitf.pt
     - Location:   (line 29: col 36)
     - Source:     tal:attributes="class view/variacao_titulo">
                                         ^^^^^^^^^^^^^^^^^^^^
     - Arguments:  context: <ImplicitAcquisitionWrapper home at 0xe95e464>
                   repeat: {...} (0)
                   description: <NoneType - at 0x81aa514>
                   views: <ViewMapper - at 0xb40d1bacL>
                   modules: <TraversableModuleImporter - at 0xa29684c>
                   args: <tuple - at 0xb74d302cL>
                   is_empty: <instancemethod is_empty at 0xd2589b4>
                   htmltag: h2
                   nothing: <NoneType - at 0x81aa514>
                   target_language: <NoneType - at 0x81aa514>
                   title: A Comissão de Ética Pública abre as inscrições par...
                   default: <object - at 0xb74f27f0L>
                   request: <instance - at 0xb41112ccL>
                   wrapped_repeat: {...} (1)
                   field: {...} (4)
                   toLocalizedTime: <instancemethod toLocalizedTime at 0xd63c5f4>
                   loop: {...} (1)
                   template: <ViewPageTemplateFile - at 0xb419c36cL>
                   translate: <function translate at 0xeb851b4>
                   options: {...} (0)
                   view: <NITFBasicTile nitf at 0xb419c1ccL>
    2014-12-12 12:05:00 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
    Traceback (most recent call last):
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/plone.transformchain-1.0.3-py2.7.egg/plone/transformchain/transformer.py", line 48, in __call__
        newResult = handler.transformIterable(result, encoding)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/plone.app.blocks-1.1.1-py2.7.egg/plone/app/blocks/transform.py", line 152, in transformIterable
        result.tree = tiles.renderTiles(self.request, result.tree)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/plone.app.blocks-1.1.1-py2.7.egg/plone/app/blocks/tiles.py", line 51, in renderTiles
        tileTree = utils.resolve(tileHref)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/plone.app.blocks-1.1.1-py2.7.egg/plone/app/blocks/utils.py", line 50, in resolve
        resolved = resolveResource(url)
      File "/home/xxx/sites/idg1.0.5/buildout-cache/eggs/plone.app.blocks-1.1.1-py2.7.egg/plone/app/blocks/utils.py", line 73, in resolveResource
        raise RuntimeError(resolved)
    RuntimeError: u'Gigante'
    
     - Expression: "view/variacao_titulo"
     - Filename:   ... 1.0.5-py2.7.egg/brasil/gov/tiles/tiles/templates/nitf.pt
     - Location:   (line 29: col 36)
     - Source:     tal:attributes="class view/variacao_titulo">
                                         ^^^^^^^^^^^^^^^^^^^^
     - Arguments:  context: <ImplicitAcquisitionWrapper home at 0xe95e464>
                   repeat: {...} (0)
                   description: <NoneType - at 0x81aa514>
                   views: <ViewMapper - at 0xb40d1bacL>
                   modules: <TraversableModuleImporter - at 0xa29684c>
                   args: <tuple - at 0xb74d302cL>
                   is_empty: <instancemethod is_empty at 0xd2589b4>
                   htmltag: h2
                   nothing: <NoneType - at 0x81aa514>
                   target_language: <NoneType - at 0x81aa514>
                   title: A Comiss\xe3o de \xc9tica P\xfablica abre as inscri\xe7\xf5es par...
                   default: <object - at 0xb74f27f0L>
                   request: <instance - at 0xb41112ccL>
                   wrapped_repeat: {...} (1)
                   field: {...} (4)
                   toLocalizedTime: <instancemethod toLocalizedTime at 0xd63c5f4>
                   loop: {...} (1)
                   template: <ViewPageTemplateFile - at 0xb419c36cL>
                   translate: <function translate at 0xeb851b4>
                   options: {...} (0)
                   view: <NITFBasicTile nitf at 0xb419c1ccL>Traceback (innermost last):
    
      Module plone.subrequest, line 124, in subrequest
    
      Module ZPublisher.mapply, line 78, in mapply
    
      Module plone.tiles.esi, line 56, in __call__
    
      Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
    
      Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
    
      Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    
      Module five.pt.engine, line 93, in __call__
    
      Module z3c.pt.pagetemplate, line 163, in render
    
      Module chameleon.zpt.template, line 258, in render
    
      Module chameleon.template, line 188, in render
    
      Module chameleon.template, line 170, in render
    
      Module 85ff51296b9e31180df64c2e6b517d11.py, line 352, in render
    
      Module five.pt.expressions, line 161, in __call__
    
      Module brasil.gov.tiles.tiles.nitf, line 72, in variacao_titulo
    
    KeyError: (see above)

Isso ocorre porque o commit https://github.com/plonegovbr/brasil.gov.tiles/commit/5430d930a3e6ed8fb739eb9562c488d50ea452ca#diff-d7ec41297fb5df1391d290cb2fcf81cbR69 alterou o dicionário 'tamanhos' com os termos em inglês, mas o que estava salvo antes eram o termos em português.

É necessário cria um upgrade step para alterar os temos em português para os temos em inglês, para tiles já existentes.

**Comment by idgserpro** [comment]
@Dadlo 
@hvelarde 

Considerenado que a internacionalização ficará para 'ação futura', a correção em https://github.com/plonegovbr/brasil.gov.tiles/pull/124 resolve o problema desse relato. No entanto, acho interessante criar um teste que verifica se os items da variável  ```variacao_titulo``` e do schema estão em português. Assim, no futuro, quando for feita a internacionalização, esse novo teste irá falhar, alertando que um upgrade step será necessário para alterar os temos em português para os temos em inglês, para tiles já existentes. Isso irá previnir que esse erro ocorra novamente no futuro.
