### ISSUE TITLE
Ao adicionar tiles "Carrossel" e "Carrossel Multimídia" numa mesma capa, dá conflito no objeto "Galleria"

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#168]
Tile Carrossel apenas:

![selecao_009](https://cloud.githubusercontent.com/assets/8203476/24669820/33a859fe-1942-11e7-8f88-8b4b9a68aaac.jpg)

Tile Carrossel Multimídia apenas:

![selecao_010](https://cloud.githubusercontent.com/assets/8203476/24669829/3a461b5c-1942-11e7-81ca-8a4d1406bb79.jpg)

Tile Carrossel e Carrossel Multimídia:

![selecao_011](https://cloud.githubusercontent.com/assets/8203476/24669840/433eca42-1942-11e7-8f1d-4a50c7cc21a9.jpg)

Traceback:

```
Uncaught TypeError: Cannot read property 'top' of null
    at Galleria.<anonymous> (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++brasil.gov.tiles/tiles.js:426:99)
    at HTMLDivElement.<anonymous> (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++collective.galleria.js:4120:23)
    at HTMLDivElement.dispatch (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:3:4816)
    at HTMLDivElement.i (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:3:709)
    at Object.trigger (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:3:3422)
    at HTMLDivElement.<anonymous> (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:3:11098)
    at Function.each (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:2:11776)
    at init.each (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:2:8304)
    at init.trigger (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:3:11074)
    at Galleria.trigger (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++collective.galleria.js:3789:31)

Uncaught TypeError: Cannot read property 'top' of null
    at Galleria.<anonymous> (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++brasil.gov.tiles/tiles.js:398:99)
    at HTMLDivElement.<anonymous> (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++collective.galleria.js:4120:23)
    at HTMLDivElement.dispatch (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:3:4816)
    at HTMLDivElement.i (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:3:709)
    at Object.trigger (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:3:3422)
    at HTMLDivElement.<anonymous> (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:3:11098)
    at Function.each (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:2:11776)
    at init.each (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:2:8304)
    at init.trigger (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.jquery.js:3:11074)
    at Galleria.trigger (http://idg:9877/Plone/portal_javascripts/Sunburst%20Theme/++resource++collective.galleria.js:3789:31)
```

Referências no código:

Onde ocorre o erro no browser: https://github.com/plonegovbr/brasil.gov.tiles/blob/f09236c3ebfde2c52fb4117fde127cca2eb0d4fb/src/brasil/gov/tiles/static/tiles.js#L426

Onde o mediacarousel instancia o objeto do carrossel: https://github.com/plonegovbr/brasil.gov.tiles/blob/caa250e9c3428d000174368321c42dae2fb48f92/src/brasil/gov/tiles/tiles/mediacarousel.py#L156

Onde o carrossel (do cover) instancia o objeto do carrossel: https://github.com/collective/collective.cover/blob/e23fed6b55222c54e5f16cb8631a74faddf56616/src/collective/cover/tiles/carousel.py#L22

Testado no release 1.1.5.2 do IDG. @rodfersou, faz muito tempo que você mexeu, mas se tiver alguma idéia, fique à vontade. `var mediacarousel = '#'+this._target.id;` em `Galleria.on('loadfinish'` em https://github.com/plonegovbr/brasil.gov.tiles/blob/f09236c3ebfde2c52fb4117fde127cca2eb0d4fb/src/brasil/gov/tiles/static/tiles.js#L426 é executado duas vezes, uma hora tendo a variável `mediacarousel` de valor `#` e outra com `#mediacarousel-gallerie-c18bb5038de84eceb9a5dc7b99b9931b'`, por isso tentar obter `.top` do elemento retorna `null` na primeira tentativa.

**Comment by hvelarde** [comment]
esse problema ainda acontece?
