### ISSUE TITLE
" error: Internal Server Error " na Tile Collection após migrar versão do IDG 1.0.5 > 1.5.3

### ISSUE THREAD

**Issue by AlexandreChagas** [plonegovbr/brasil.gov.tiles#273]
Foi efetuada uma migração do portal, da versão do IDG 1.0.5 > 1.5.3, aparentemente tudo ocorreu bem, exceto, nas Tiles Collection não são carregadas.
Quanto a coleção e seu conteúdo, foram testados, inclusive a imagem que aparece na mensagem de erro.

Prosseguindo com a sugestão do Davi:
Talvez o chamado dessa tile possa ser protegida no método getImage, visando os casos em que a imagem não é encontrada. No caso a tile exibiria sem a imagem, e não daria esse erro.

![image](https://user-images.githubusercontent.com/8559384/61053147-5914db00-a3c3-11e9-88f2-2d76c827d4dc.png)

Alexandre Chagas

**Comment by AlexandreChagas** [comment]
![image](https://user-images.githubusercontent.com/8559384/61053427-e6f0c600-a3c3-11e9-9735-04ca741fd055.png)

2019-07-10 16:55:29 ERROR plone.subrequest Error handling subrequest to http://10.1.20.41:8082/portal/sti/home/@@collective.cover.collection/ae131c40f1f54dcea5f12eb88c7379a7
Traceback (most recent call last):
  File "/opt/Plone-4.3.18/buildout-cache/eggs/plone.subrequest-1.8.5-py2.7.egg/plone/subrequest/__init__.py", line 156, in subrequest
    bind=1
  File "/opt/Plone-4.3.18/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/mapply.py", line 78, in mapply
    else: return object(*args)
  File "/opt/Plone-4.3.18/buildout-cache/eggs/plone.tiles-2.1-py2.7.egg/plone/tiles/esi.py", line 87, in __call__
    return self.index(*args, **kwargs)
  File "/opt/Plone-4.3.18/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/opt/Plone-4.3.18/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/opt/Plone-4.3.18/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/opt/Plone-4.3.18/buildout-cache/eggs/five.pt-2.2.5-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/opt/Plone-4.3.18/buildout-cache/eggs/z3c.pt-3.0-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/opt/Plone-4.3.18/buildout-cache/eggs/Chameleon-2.25-py2.7.egg/chameleon/zpt/template.py", line 261, in render
    return super(PageTemplate, self).render(**vars)
  File "/opt/Plone-4.3.18/buildout-cache/eggs/Chameleon-2.25-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/opt/Plone-4.3.18/buildout-cache/eggs/Chameleon-2.25-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "7df445e210ca58e77f15e8977e2313f2.py", line 468, in render
  File "/opt/Plone-4.3.18/buildout-cache/eggs/brasil.gov.tiles-1.6.1-py2.7.egg/brasil/gov/tiles/tiles/collection.py", line 217, in get_alt
    image = obj.getImage()
AttributeError: getImage

 - Expression: "python:view.get_alt(obj)"
 - Filename:   ... py2.7.egg/brasil/gov/tiles/tiles/templates/collection.pt
 - Location:   (line 36: col 62)
 - Source:     alt python:view.get_alt(obj);" />
                   ^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  modules: <instance - at 0x7fbeb7fcd950>
               results: <ContentListing - at 0x7fbea96882d0>
               container: <ImplicitAcquisitionWrapper home at 0x7fbeacbc74b0>
               wrapped_repeat: <SafeMapping - at 0x7fbea9924d08>
               traverse_subpath: <list - at 0x7fbea93ef2d8>
               field: image
               template: <ViewPageTemplateFile - at 0x7fbeab24b9d0>
               translate: <function translate at 0x7fbeaa50ba28>
               config: {...} (2)
               thumbnail: <ImageScale 61466875-4d68-4fe3-8267-397cf27f69eb.png at 0x7fbea97775d0>
               repeat: {...} (0)
               views: <ViewMapper - at 0x7fbea96dcd90>
               args: <tuple - at 0x7fbec32d6050>
               here: <ImplicitAcquisitionWrapper home at 0x7fbeacbc74b0>
               is_empty: False
               user: <ImplicitAcquisitionWrapper - at 0x7fbeacbc7870>
               nothing: <NoneType - at 0x789a10>
               conf_fields: {...} (9)
               obj: <ImplicitAcquisitionWrapper posic-sua-senha-vai-expirar-saiba-como-criar-uma-senha-segura at 0x7fbeacd2ba00>
               default: <object - at 0x7fbec32acba0>
               request: <instance - at 0x7fbea945e680>
               item: <CatalogContentListingObject - at 0x7fbea9688d90>
               toLocalizedTime: <instancemethod toLocalizedTime at 0x7fbeacb7ce60>
               loop: {...} (2)
               context: <ImplicitAcquisitionWrapper home at 0x7fbeacbc74b0>
               view: <CollectionTile collective.cover.collection at 0x7fbea96883d0>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fbeacb9ea50>
               options: {...} (0)
               target_language: <NoneType - at 0x789a10>
